name = "pi-sensor"
update_interval = 60

[si7021]
enabled = true

[disk]
enabled = true

[cpu]
enabled = true

[mem]
enabled = true

[mqtt]
enabled = false
endpoint = "iot.eclipse.org"
port = 1883

[awsiot]
enabled = false
endpoint = "a2ilo8j9t13k8m.iot.us-east-1.amazonaws.com"
cert = "/etc/aws/pi-sensor.cert.pem"
key = "/etc/aws/pi-sensor.private.key"
ca = "/etc/aws/root-CA.crt"

[rfm69]
enabled = false
high_power = true
network = 1
node = 1
gateway = 254
encryption_key = "1234567891011121"
