name = "pi-sensor"


[si7021]
enabled = true

[disk]
enabled = true

[cpu]
enabled = true

[mem]
enabled = true

[web]
enabled = false
port = 80

[mqtt]
enabled = false
endpoint = "iot.eclipse.org"
port = 1883

[awsiot]
enabled = false
endpoint = "a2ilo8j9t13k8m.iot.us-east-1.amazonaws.com"
cert = "/etc/aws/pi-sensor.cert.pem"
key = "/etc/aws/pi-sensor.private.key"
ca = "/etc/aws/root-CA.crt"

[rfm69]
enabled = false
high_power = true
network = 1
node = 1
gateway = 254
encryption_key = "1234567891011121"

[websocket]
enabled = false
endpoint = "gateway.example.com"
port = 8765

[camera]
enabled = false
resolution = "800x600"
fps = 5
rotation = 0
shutter_speed = 0
sensor_mode = 3
exposure_mode = "night"
use_video_port = true
