name = "pi-sensor"
update_interval = 60

[si7021]
enabled = true

[disk]
enabled = true

[cpu]
enabled = true

[mem]
enabled = true

[awsiot]
enabled = true
endpoint = "a2ilo8j9t13k8m.iot.us-east-1.amazonaws.com"
cert = "/etc/aws/pi-sensor.cert.pem"
key = "/etc/aws/pi-sensor.private.key"
ca = "/etc/aws/root-CA.crt"

